version: "3"
services:
  server:
    restart: always
    container_name: mern_server
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
  mongodb:
    container_name: mern_mongo
    restart: always
    image: mongo:4.2.0
    expose:
      - "27017"
    volumes:
      - ./db:/data/db
  frontend:
    restart: always
    container_name: mern_frontend
    build:
      context: ./frontend/
    ports:
      - 3000:3000
